### ISSUE TITLE
Test depositEth and withdrawEth.

### ISSUE THREAD

**Issue by liderako** [liderako/eth_contracts#3]
1. Test deposit and withdraw Eth in exchange smart-contact

**Comment by asvirido** [comment]
__

**Comment by liderako** [comment]
Protected if balance < amount. Done. [Withdraw]

**Comment by liderako** [comment]
Protected if amount == 0. Done. [Withdraw]

**Comment by liderako** [comment]
Check when all user balance == 0 after withdraw. [Withdraw]

**Comment by liderako** [comment]
Protected if amount == 0. Done. [Deposit]

**Comment by liderako** [comment]
Protected if overflow. Overflow when (amount == balance) and amount == max_uint and balance == max_uint. This is impossible
